### ISSUE TITLE
小白如何运行

### ISSUE THREAD

**Issue by ethanchengyu** [reycn/cubox-to-notion#1]
下载好了，不会运行，求指导
<img width="392" alt="image" src="https://user-images.githubusercontent.com/25861044/186424096-667c77c9-d070-46f6-beb5-81e8a1977b6d.png">
<img width="458" alt="image" src="https://user-images.githubusercontent.com/25861044/186424341-f1068ac7-f785-4074-ad79-7dc6924765f9.png">

**Comment by reycn** [comment]
之后会写详细一点的文档，但不提供技术支持哈。
非官方 api 使用太广也会影响到项目稳定性的。
