### ISSUE TITLE
运行出现错误，已填写却提示config缺少token

### ISSUE THREAD

**Issue by Mivimcrs** [reycn/cubox-to-notion#5]
已根据教程填写了 Notion 的机器人 API token 和文件夹的 id，仍然提示 `[cubox_to_notion] ERROR: [Notion] No valid token or database found in config.ini` ，这种情况要怎么弄？😂

**Comment by Ma-hy** [comment]
> 

如果是按模版来的，后面不要有注释。
另外不要忘了在Notion的数据库页面中把本页面分享给创建的机器人，不然还是会提示找不到数据库。

**Comment by Mivimcrs** [comment]
![image](https://user-images.githubusercontent.com/40280036/188316657-b0e5c030-18e0-4775-860e-deb1536124f5.png)
![image](https://user-images.githubusercontent.com/40280036/188316850-53bb72c7-6082-496c-b786-834f9b6e322d.png)
![image](https://user-images.githubusercontent.com/40280036/188317122-bba749ea-20aa-44c3-876f-b05fd3108286.png)
已经邀请机器人了，文档也删除所有注释，还是不行

**Comment by Ma-hy** [comment]
是不是Notion机器人的权限不够？需要有写入权限
![image](https://user-images.githubusercontent.com/17977287/188319796-095ba9a2-1ace-495a-925c-633735825e95.png)

**Comment by Ma-hy** [comment]
还有你的Cubox文件夹里面是不是空的？

**Comment by Benature** [comment]
```python
articles = json.loads(response.body)["data"]
```
这里报错也会通知 `[Notion] No valid token or database found in config.ini`
其实也有可能是 Cubox token 有问题

```
{'code': -1006, 'message': 'token error!'}
```

**Comment by reycn** [comment]
按照上述建议检查下就可以，我暂时没有想象到其他可能。

**Comment by Mivimcrs** [comment]
破案了，我以为是用 Cubox 的智能文件夹，原来是用收藏夹。今天看到大家回复的方法检查了一遍，最后试了换成收藏夹就成功了！非常棒的程序！！

**Comment by reycn** [comment]
十月更新已经明确该类提醒。
