### ISSUE TITLE
将网页全文写进Notion page中、增加一列创建时间

### ISSUE THREAD

**Issue by Benature** [reycn/cubox-to-notion#7]
感谢分享，如果可以把收藏的网页全文写入到Notion page就更好了，目前应该只是网页的概述。这样就可以免费无限制做笔记高亮了。

另外希望可以增加收藏进Cubox的时间，这样在notion可以方便排序。

**Comment by Benature** [comment]
哦哦哦，刚看到 https://github.com/users/reycn/projects/1 有 Full text support，应该和第一点是一个意思了🫡

**Comment by reycn** [comment]
嗯，在计划中。
